namespace RenoTrack.Website.Tests.Site;

/// <summary>
/// Real fixture derivatives (generated by <c>tools/RenoTrack.MediaPrep</c> from synthetic test graphics) and byte
/// surgery on them, so each refusal is proven against an otherwise valid file (<b>D106</b>).
/// </summary>
internal static class MediaBytes
{
    internal static string FixtureMediaRoot =>
        Path.Combine(TemporaryContentPack.FixtureRoot(TemporaryContentPack.Alpha), "media");

    internal static byte[] Fixture(string fileName) => File.ReadAllBytes(Path.Combine(FixtureMediaRoot, fileName));

    internal static byte[] Jpeg => Fixture("testbild-startseite-480.jpg");

    internal static byte[] WebP => Fixture("testbild-startseite-480.webp");

    /// <summary>Inserts a JPEG segment directly after SOI.</summary>
    internal static byte[] WithJpegSegment(byte[] jpeg, byte marker, byte[] payload)
    {
        var length = payload.Length + 2;
        byte[] header = [0xFF, marker, (byte)(length >> 8), (byte)length];
        return [.. jpeg[..2], .. header, .. payload, .. jpeg[2..]];
    }

    internal static byte[] Ascii(string text) => System.Text.Encoding.ASCII.GetBytes(text);

    /// <summary>A minimal EXIF APP1 payload with a GPS IFD pointer, as a phone writes it.</summary>
    internal static byte[] ExifPayload() =>
        [.. Ascii("Exif\0\0II*\0"), 8, 0, 0, 0, 1, 0, 0x25, 0x88, 4, 0, 1, 0, 0, 0, 26, 0, 0, 0, 0, 0, 0, 0];

    /// <summary>Rebuilds a simple (VP8) WebP as extended (VP8X) with the given flags and extra chunks after the bitstream.</summary>
    internal static byte[] ExtendedWebP(byte[] simpleWebP, byte flags, params (string FourCc, byte[] Data)[] extraChunks)
    {
        var bitstream = simpleWebP[12..];
        var chunks = new List<byte>();

        byte[] vp8x = new byte[10];
        vp8x[0] = flags;
        chunks.AddRange(Chunk("VP8X", vp8x));
        chunks.AddRange(bitstream);
        foreach (var (fourCc, data) in extraChunks)
        {
            chunks.AddRange(Chunk(fourCc, data));
        }

        return Riff(chunks.ToArray());
    }

    /// <summary>A WebP RIFF container around <paramref name="chunks"/>, with a correct size.</summary>
    internal static byte[] Riff(byte[] chunks)
    {
        var size = chunks.Length + 4;
        return [.. Ascii("RIFF"), (byte)size, (byte)(size >> 8), (byte)(size >> 16), (byte)(size >> 24), .. Ascii("WEBP"), .. chunks];
    }

    internal static byte[] Chunk(string fourCc, byte[] data)
    {
        var padded = data.Length % 2 == 1 ? [.. data, 0] : data;
        return [.. Ascii(fourCc), (byte)data.Length, (byte)(data.Length >> 8), (byte)(data.Length >> 16), (byte)(data.Length >> 24), .. padded];
    }
}
